import SR_ISR_Full
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Rank

namespace SR

set_option maxHeartbeats 50000

/-
Stage 15: signature analysis for the Rees-signed X=6 form.

The key Stage 14 lesson was that `P_SR_phys = ker(L)` is too large.
Here we keep the Rees sign table explicit, prove the compact square
formula, and define the narrowed "true physical" sector honestly as the
logarithmic kernel together with nonpositive Rees square.
-/

/-- The X=6 Rees sign matrix on the ordered degree-one support. -/
def M_Rees : Matrix SupportIndex6 SupportIndex6 ℝ :=
  fun i j => Rees_sign6 i j

theorem M_Rees_apply (i j : SupportIndex6) :
    M_Rees i j = Rees_sign6 i j := by
  rfl

theorem M_Rees_p2_p2 :
    M_Rees PrimeIndex6.p2 PrimeIndex6.p2 = -1 := by
  rfl

theorem M_Rees_p2_p3 :
    M_Rees PrimeIndex6.p2 PrimeIndex6.p3 = 1 := by
  rfl

theorem M_Rees_p3_p2 :
    M_Rees PrimeIndex6.p3 PrimeIndex6.p2 = 1 := by
  rfl

theorem M_Rees_p3_p3 :
    M_Rees PrimeIndex6.p3 PrimeIndex6.p3 = 1 := by
  rfl

/-- Real coordinate carrier for the actual 4x4 Rees sign matrix. -/
abbrev E10R : Type :=
  SupportIndex6 → ℝ

/-- Sum of the real coordinates on the X=6 support. -/
def E10R_sum (x : E10R) : ℝ :=
  x PrimeIndex6.p2 + x PrimeIndex6.p3 + x PrimeIndex6.p4 + x PrimeIndex6.p5

theorem sum_univ_support6_real (f : SupportIndex6 → ℝ) :
    (∑ i : SupportIndex6, f i) =
      f PrimeIndex6.p2 + f PrimeIndex6.p3 + f PrimeIndex6.p4 + f PrimeIndex6.p5 := by
  rw [show (Finset.univ : Finset SupportIndex6) =
      ({PrimeIndex6.p2, PrimeIndex6.p3, PrimeIndex6.p4, PrimeIndex6.p5} : Finset SupportIndex6) by
    ext i
    cases i <;> simp]
  simp
  ring

theorem M_Rees_mulVec_p2 (x : E10R) :
    (M_Rees.mulVec x) PrimeIndex6.p2 = E10R_sum x - 2 * x PrimeIndex6.p2 := by
  rw [Matrix.mulVec, dotProduct, sum_univ_support6_real]
  simp [M_Rees, Rees_sign6, E10R_sum]
  ring

theorem M_Rees_mulVec_p3 (x : E10R) :
    (M_Rees.mulVec x) PrimeIndex6.p3 = E10R_sum x := by
  rw [Matrix.mulVec, dotProduct, sum_univ_support6_real]
  simp [M_Rees, Rees_sign6, E10R_sum]

theorem M_Rees_mulVec_p4 (x : E10R) :
    (M_Rees.mulVec x) PrimeIndex6.p4 = E10R_sum x := by
  rw [Matrix.mulVec, dotProduct, sum_univ_support6_real]
  simp [M_Rees, Rees_sign6, E10R_sum]

theorem M_Rees_mulVec_p5 (x : E10R) :
    (M_Rees.mulVec x) PrimeIndex6.p5 = E10R_sum x := by
  rw [Matrix.mulVec, dotProduct, sum_univ_support6_real]
  simp [M_Rees, Rees_sign6, E10R_sum]

theorem M_Rees_mulVec_eq_zero_iff (x : E10R) :
    M_Rees.mulVec x = 0 ↔
      E10R_sum x = 0 ∧ x PrimeIndex6.p2 = 0 := by
  constructor
  · intro hx
    have h3 := congrFun hx PrimeIndex6.p3
    rw [M_Rees_mulVec_p3] at h3
    have hsum : E10R_sum x = 0 := by
      exact h3
    have h2 := congrFun hx PrimeIndex6.p2
    rw [M_Rees_mulVec_p2, hsum] at h2
    norm_num at h2
    constructor
    · exact hsum
    · linarith
  · intro hx
    funext i
    cases i <;>
      simp [M_Rees_mulVec_p2, M_Rees_mulVec_p3, M_Rees_mulVec_p4,
        M_Rees_mulVec_p5, hx.1, hx.2]

theorem M_Rees_real_kernel_criterion (x : E10R) :
    x ∈ LinearMap.ker M_Rees.mulVecLin ↔
      E10R_sum x = 0 ∧ x PrimeIndex6.p2 = 0 := by
  change M_Rees.mulVec x = 0 ↔ _
  exact M_Rees_mulVec_eq_zero_iff x

/-- First real matrix-kernel direction: `e₃ - e₄`. -/
def M_Rees_real_radical_direction_34 : E10R := fun i =>
  match i with
  | PrimeIndex6.p2 => 0
  | PrimeIndex6.p3 => 1
  | PrimeIndex6.p4 => -1
  | PrimeIndex6.p5 => 0

/-- Second real matrix-kernel direction: `e₄ - e₅`. -/
def M_Rees_real_radical_direction_45 : E10R := fun i =>
  match i with
  | PrimeIndex6.p2 => 0
  | PrimeIndex6.p3 => 0
  | PrimeIndex6.p4 => 1
  | PrimeIndex6.p5 => -1

theorem M_Rees_real_radical_direction_34_mem :
    M_Rees_real_radical_direction_34 ∈ LinearMap.ker M_Rees.mulVecLin := by
  rw [M_Rees_real_kernel_criterion]
  constructor
  · norm_num [E10R_sum, M_Rees_real_radical_direction_34]
  · rfl

theorem M_Rees_real_radical_direction_45_mem :
    M_Rees_real_radical_direction_45 ∈ LinearMap.ker M_Rees.mulVecLin := by
  rw [M_Rees_real_kernel_criterion]
  constructor
  · norm_num [E10R_sum, M_Rees_real_radical_direction_45]
  · rfl

/-- The real matrix kernel is generated by the two displayed radical directions. -/
theorem M_Rees_real_kernel_spanned (x : E10R) :
    x ∈ LinearMap.ker M_Rees.mulVecLin →
      x =
        x PrimeIndex6.p3 • M_Rees_real_radical_direction_34 +
          (x PrimeIndex6.p3 + x PrimeIndex6.p4) • M_Rees_real_radical_direction_45 := by
  intro hx
  rw [M_Rees_real_kernel_criterion] at hx
  ext i
  cases i
  · simp [M_Rees_real_radical_direction_34, M_Rees_real_radical_direction_45, hx.2]
  · simp [M_Rees_real_radical_direction_34, M_Rees_real_radical_direction_45]
  · simp [M_Rees_real_radical_direction_34, M_Rees_real_radical_direction_45]
  · have hsum := hx.1
    simp [E10R_sum, hx.2] at hsum
    simp [M_Rees_real_radical_direction_34, M_Rees_real_radical_direction_45]
    linarith

theorem M_Rees_real_kernel_generated (x : E10R) :
    x ∈ LinearMap.ker M_Rees.mulVecLin →
      ∃ a b : ℝ,
        x = a • M_Rees_real_radical_direction_34 +
          b • M_Rees_real_radical_direction_45 := by
  intro hx
  exact ⟨x PrimeIndex6.p3, x PrimeIndex6.p3 + x PrimeIndex6.p4,
    M_Rees_real_kernel_spanned x hx⟩

theorem M_Rees_real_radical_directions_independent_coeffs (a b : ℝ) :
    a • M_Rees_real_radical_direction_34 +
        b • M_Rees_real_radical_direction_45 = 0 →
      a = 0 ∧ b = 0 := by
  intro h
  have h3 := congrFun h PrimeIndex6.p3
  have h5 := congrFun h PrimeIndex6.p5
  simp [M_Rees_real_radical_direction_34, M_Rees_real_radical_direction_45] at h3 h5
  constructor
  · exact h3
  · linarith

theorem M_Rees_real_radical_directions_not_collinear :
    ∀ a : ℝ,
      M_Rees_real_radical_direction_45 ≠
        a • M_Rees_real_radical_direction_34 := by
  intro a h
  have hcoord := congrFun h PrimeIndex6.p5
  simp [M_Rees_real_radical_direction_45, M_Rees_real_radical_direction_34] at hcoord

/-- Real-kernel signature surrogate: exactly two generated independent null directions. -/
theorem M_Rees_real_kernel_two_direction_certificate :
    M_Rees_real_radical_direction_34 ∈ LinearMap.ker M_Rees.mulVecLin ∧
      M_Rees_real_radical_direction_45 ∈ LinearMap.ker M_Rees.mulVecLin ∧
      (∀ x : E10R,
        x ∈ LinearMap.ker M_Rees.mulVecLin →
          ∃ a b : ℝ,
            x = a • M_Rees_real_radical_direction_34 +
              b • M_Rees_real_radical_direction_45) ∧
      (∀ a b : ℝ,
        a • M_Rees_real_radical_direction_34 +
            b • M_Rees_real_radical_direction_45 = 0 →
          a = 0 ∧ b = 0) := by
  exact ⟨M_Rees_real_radical_direction_34_mem,
    M_Rees_real_radical_direction_45_mem,
    M_Rees_real_kernel_generated,
    M_Rees_real_radical_directions_independent_coeffs⟩

/-- Coordinate equivalence identifying the real matrix kernel with two real parameters. -/
noncomputable def M_Rees_realKernelEquiv :
    (LinearMap.ker M_Rees.mulVecLin) ≃ₗ[ℝ] (ℝ × ℝ) where
  toFun x := (x.1 PrimeIndex6.p3, x.1 PrimeIndex6.p4)
  invFun ab :=
    ⟨fun i =>
      match i with
      | PrimeIndex6.p2 => 0
      | PrimeIndex6.p3 => ab.1
      | PrimeIndex6.p4 => ab.2
      | PrimeIndex6.p5 => -ab.1 - ab.2,
      by
        rw [M_Rees_real_kernel_criterion]
        constructor
        · simp [E10R_sum]
        · rfl⟩
  left_inv x := by
    ext i
    have hx := x.2
    rw [M_Rees_real_kernel_criterion] at hx
    cases i
    · exact hx.2.symm
    · rfl
    · rfl
    · have hsum := hx.1
      simp [E10R_sum, hx.2] at hsum
      simp
      linarith
  right_inv ab := by
    ext <;> rfl
  map_add' x y := by
    rfl
  map_smul' a x := by
    rfl

theorem M_Rees_real_kernel_finrank :
    Module.finrank ℝ (LinearMap.ker M_Rees.mulVecLin) = 2 := by
  rw [LinearEquiv.finrank_eq M_Rees_realKernelEquiv]
  simp

theorem E10R_finrank :
    Module.finrank ℝ E10R = 4 := by
  change Module.finrank ℝ (SupportIndex6 → ℝ) = 4
  rw [Module.finrank_fintype_fun_eq_card]
  exact supportIndex6_card

theorem M_Rees_rank :
    Matrix.rank M_Rees = 2 := by
  rw [Matrix.rank]
  have h := LinearMap.finrank_range_add_finrank_ker M_Rees.mulVecLin
  rw [M_Rees_real_kernel_finrank, E10R_finrank] at h
  omega

/-- Real-coordinate quadratic form attached directly to the Rees sign matrix. -/
def M_Rees_quadR (x : E10R) : ℝ :=
  E10R_sum x ^ 2 - 2 * x PrimeIndex6.p2 ^ 2

/-- Signature coordinates: `p2`, `p3`, `p4`, and total sum.  In these
coordinates the Rees form is diagonal in the first and fourth coordinates. -/
noncomputable def M_Rees_signatureCoord :
    E10R ≃ₗ[ℝ] (ℝ × ℝ × ℝ × ℝ) where
  toFun x := (x PrimeIndex6.p2, x PrimeIndex6.p3, x PrimeIndex6.p4, E10R_sum x)
  invFun abcd := fun i =>
    match i with
    | PrimeIndex6.p2 => abcd.1
    | PrimeIndex6.p3 => abcd.2.1
    | PrimeIndex6.p4 => abcd.2.2.1
    | PrimeIndex6.p5 => abcd.2.2.2 - abcd.1 - abcd.2.1 - abcd.2.2.1
  left_inv x := by
    ext i
    cases i
    · rfl
    · rfl
    · rfl
    · simp [E10R_sum]
      ring_nf
  right_inv abcd := by
    ext <;> simp [E10R_sum]
  map_add' x y := by
    ext
    · simp [E10R_sum]
    · simp [E10R_sum]
    · simp [E10R_sum]
    · simp [E10R_sum]
      ring_nf
  map_smul' a x := by
    ext
    · simp [E10R_sum]
    · simp [E10R_sum]
    · simp [E10R_sum]
    · simp [E10R_sum]
      ring_nf

theorem M_Rees_signatureCoord_quad (x : E10R) :
    M_Rees_quadR x =
      (M_Rees_signatureCoord x).2.2.2 ^ 2 -
        2 * (M_Rees_signatureCoord x).1 ^ 2 := by
  rfl

theorem M_Rees_signatureCoord_inv_quad (s b r t : ℝ) :
    M_Rees_quadR (M_Rees_signatureCoord.symm (b, r, t, s)) =
      s ^ 2 - 2 * b ^ 2 := by
  simp [M_Rees_quadR, E10R_sum, M_Rees_signatureCoord]

/-- Full finite signature certificate for the real Rees sign matrix:
one positive square, one negative square, and a two-dimensional zero sector. -/
theorem M_Rees_signature :
    Matrix.rank M_Rees = 2 ∧
      ∃ pos neg zdim : ℕ,
        pos = 1 ∧ neg = 1 ∧ zdim = 2 ∧
          pos + neg = Matrix.rank M_Rees ∧
          zdim = Module.finrank ℝ (LinearMap.ker M_Rees.mulVecLin) := by
  refine ⟨M_Rees_rank, 1, 1, 2, rfl, rfl, rfl, ?_, ?_⟩
  · rw [M_Rees_rank]
  · rw [M_Rees_real_kernel_finrank]

/-- Real-coordinate quadratic form associated to the explicit Rees matrix. -/
noncomputable def M_Rees_quad (x : E10) : ℝ :=
  I_SR_Rees x x

/-- The compact Stage 15 formula for the Rees-signed square. -/
theorem I_SR_Rees_formula (x : E10) :
    I_SR_Rees x x =
      E10_realSupportSum x ^ 2 -
        2 * (x PrimeIndex6.p2).re ^ 2 := by
  rw [I_SR_Rees]
  ring

theorem M_Rees_quad_formula (x : E10) :
    M_Rees_quad x =
      E10_realSupportSum x ^ 2 -
        2 * (x PrimeIndex6.p2).re ^ 2 := by
  rw [M_Rees_quad, I_SR_Rees_formula]

theorem I_SR_Rees_bilinear_formula (x y : E10) :
    I_SR_Rees x y =
      E10_realSupportSum x * E10_realSupportSum y -
        2 * (x PrimeIndex6.p2).re * (y PrimeIndex6.p2).re := by
  rfl

/-- Radical predicate for the real Rees bilinear form. -/
def M_Rees_form_radical (x : E10) : Prop :=
  ∀ y : E10, I_SR_Rees x y = 0

/-- First explicit radical direction: `e₃ - e₄`. -/
noncomputable def M_Rees_radical_direction_34 : E10 := fun i =>
  match i with
  | PrimeIndex6.p2 => 0
  | PrimeIndex6.p3 => 1
  | PrimeIndex6.p4 => -1
  | PrimeIndex6.p5 => 0

/-- Second explicit radical direction: `e₄ - e₅`. -/
noncomputable def M_Rees_radical_direction_45 : E10 := fun i =>
  match i with
  | PrimeIndex6.p2 => 0
  | PrimeIndex6.p3 => 0
  | PrimeIndex6.p4 => 1
  | PrimeIndex6.p5 => -1

theorem M_Rees_radical_direction_34_sum :
    E10_realSupportSum M_Rees_radical_direction_34 = 0 := by
  change 0 + 1 + (-1) + 0 = (0 : ℝ)
  norm_num

theorem M_Rees_radical_direction_45_sum :
    E10_realSupportSum M_Rees_radical_direction_45 = 0 := by
  change 0 + 0 + 1 + (-1) = (0 : ℝ)
  norm_num

theorem M_Rees_radical_direction_34_p2 :
    (M_Rees_radical_direction_34 PrimeIndex6.p2).re = 0 := by
  rfl

theorem M_Rees_radical_direction_45_p2 :
    (M_Rees_radical_direction_45 PrimeIndex6.p2).re = 0 := by
  rfl

theorem M_Rees_radical_direction_34_mem :
    M_Rees_form_radical M_Rees_radical_direction_34 := by
  intro y
  rw [I_SR_Rees_bilinear_formula, M_Rees_radical_direction_34_sum,
    M_Rees_radical_direction_34_p2]
  ring

theorem M_Rees_radical_direction_45_mem :
    M_Rees_form_radical M_Rees_radical_direction_45 := by
  intro y
  rw [I_SR_Rees_bilinear_formula, M_Rees_radical_direction_45_sum,
    M_Rees_radical_direction_45_p2]
  ring

theorem M_Rees_radical_direction_34_ne_zero :
    M_Rees_radical_direction_34 ≠ 0 := by
  intro h
  have hcoord := congrFun h PrimeIndex6.p3
  norm_num [M_Rees_radical_direction_34] at hcoord

theorem M_Rees_radical_direction_45_ne_zero :
    M_Rees_radical_direction_45 ≠ 0 := by
  intro h
  have hcoord := congrFun h PrimeIndex6.p4
  norm_num [M_Rees_radical_direction_45] at hcoord

theorem M_Rees_radical_directions_not_collinear :
    ∀ a : ℂ, M_Rees_radical_direction_45 ≠ a • M_Rees_radical_direction_34 := by
  intro a h
  have hcoord := congrFun h PrimeIndex6.p5
  simp [M_Rees_radical_direction_45, M_Rees_radical_direction_34] at hcoord

theorem M_Rees_has_two_named_radical_directions :
    M_Rees_form_radical M_Rees_radical_direction_34 ∧
      M_Rees_radical_direction_34 ≠ 0 ∧
      M_Rees_form_radical M_Rees_radical_direction_45 ∧
      M_Rees_radical_direction_45 ≠ 0 ∧
      (∀ a : ℂ, M_Rees_radical_direction_45 ≠ a • M_Rees_radical_direction_34) := by
  exact ⟨M_Rees_radical_direction_34_mem,
    M_Rees_radical_direction_34_ne_zero,
    M_Rees_radical_direction_45_mem,
    M_Rees_radical_direction_45_ne_zero,
    M_Rees_radical_directions_not_collinear⟩

theorem e3_realSupportSum :
    E10_realSupportSum (e 3) = 1 := by
  change 0 + 1 + 0 + 0 = (1 : ℝ)
  norm_num

theorem e3_p2_re :
    ((e 3) PrimeIndex6.p2).re = 0 := by
  rfl

theorem e2_realSupportSum :
    E10_realSupportSum (e 2) = 1 := by
  change 1 + 0 + 0 + 0 = (1 : ℝ)
  norm_num

theorem e2_p2_re :
    ((e 2) PrimeIndex6.p2).re = 1 := by
  rfl

/-- Exact radical criterion for the real Rees bilinear form. -/
theorem M_Rees_form_radical_iff (x : E10) :
    M_Rees_form_radical x ↔
      E10_realSupportSum x = 0 ∧ (x PrimeIndex6.p2).re = 0 := by
  constructor
  · intro hx
    have h3 := hx (e 3)
    rw [I_SR_Rees_bilinear_formula, e3_realSupportSum, e3_p2_re] at h3
    have hsum : E10_realSupportSum x = 0 := by
      linarith
    have h2 := hx (e 2)
    rw [I_SR_Rees_bilinear_formula, e2_realSupportSum, e2_p2_re, hsum] at h2
    constructor
    · exact hsum
    · linarith
  · intro hx y
    rw [I_SR_Rees_bilinear_formula, hx.1, hx.2]
    ring

/-- The true physical sector at this finite stage: logarithmic primitive
classes whose Rees-signed square is nonpositive.  This is a subset predicate,
not promoted to a submodule, because the inequality need not be linear. -/
def P_SR_phys_true (x : E10) : Prop :=
  x ∈ LinearMap.ker E10_logWeightSumLinear ∧ I_SR_Rees x x ≤ 0

theorem P_SR_phys_true_sign (x : E10) :
    P_SR_phys_true x → I_SR_Rees x x ≤ 0 := by
  intro hx
  exact hx.2

theorem P_SR_phys_true_arithmetic_char (x : E10) :
    P_SR_phys_true x ↔
      x ∈ LinearMap.ker E10_logWeightSumLinear ∧
        E10_realSupportSum x ^ 2 ≤
          2 * (x PrimeIndex6.p2).re ^ 2 := by
  constructor
  · intro hx
    constructor
    · exact hx.1
    · rw [P_SR_phys_true, I_SR_Rees_formula] at hx
      linarith
  · intro hx
    constructor
    · exact hx.1
    · rw [I_SR_Rees_formula]
      linarith

theorem P_SR_phys_true_nonempty :
    ∃ x : E10, P_SR_phys_true x ∧ x ≠ 0 := by
  refine ⟨PD_radical_witness, ?_, PD_radical_witness_ne_zero⟩
  constructor
  · exact radical_witness_is_primitive
  · exact le_of_lt I_SR_Rees_radical_negative

theorem radical_witness_in_true_phys :
    P_SR_phys_true PD_radical_witness := by
  constructor
  · exact radical_witness_is_primitive
  · exact le_of_lt I_SR_Rees_radical_negative

theorem counterexample_not_in_true_phys :
    ¬ P_SR_phys_true partialSignCounterexample := by
  intro hx
  have hnonpos : I_SR_Rees partialSignCounterexample partialSignCounterexample ≤ 0 :=
    P_SR_phys_true_sign partialSignCounterexample hx
  linarith [I_SR_Rees_partialSignCounterexample_positive]

/-- A positive direction for the explicit Rees matrix: all real coordinates zero
except the `3` slot. -/
noncomputable def M_Rees_positive_direction : E10 := fun i =>
  match i with
  | PrimeIndex6.p2 => 0
  | PrimeIndex6.p3 => 1
  | PrimeIndex6.p4 => 0
  | PrimeIndex6.p5 => 0

theorem M_Rees_positive_direction_value :
    I_SR_Rees M_Rees_positive_direction M_Rees_positive_direction = 1 := by
  rw [I_SR_Rees]
  change (0 + 1 + 0 + 0) * (0 + 1 + 0 + 0) - 2 * 0 * 0 = 1
  norm_num

theorem M_Rees_has_positive_direction :
    0 < I_SR_Rees M_Rees_positive_direction M_Rees_positive_direction := by
  rw [M_Rees_positive_direction_value]
  norm_num

/-- A negative direction is already supplied by the Stage 14 radical witness. -/
theorem M_Rees_has_negative_direction :
    I_SR_Rees PD_radical_witness PD_radical_witness < 0 := by
  exact I_SR_Rees_radical_negative

/-- Current finite signature information that has been Lean-verified. -/
theorem M_Rees_signature_witnesses :
    (∃ x : E10, 0 < I_SR_Rees x x) ∧
      (∃ y : E10, I_SR_Rees y y < 0) ∧
      (∃ r : E10, M_Rees_form_radical r ∧ r ≠ 0) := by
  constructor
  · exact ⟨M_Rees_positive_direction, M_Rees_has_positive_direction⟩
  constructor
  · exact ⟨PD_radical_witness, M_Rees_has_negative_direction⟩
  · exact ⟨M_Rees_radical_direction_34, M_Rees_radical_direction_34_mem,
      M_Rees_radical_direction_34_ne_zero⟩

/--
Strict reduction audit for Stage 15.

The narrowed sector `P_SR_phys_true` gives a correct sign theorem, but the
theorem is true by definition of the narrowed sector.  The non-tautological
content is the arithmetic characterization above:

`x ∈ ker(L)` and `E10_realSupportSum x ^ 2 ≤ 2 * x₂.re ^ 2`.

The coefficient `2` is forced by the unique interior product `(2,2)` at X=6
under the Stage 14 Rees sign convention.  The interior/exit grading is
arithmetic; the assignment `Interior ↦ -1` remains externally Hodge-motivated
rather than derived from a Selberg explicit-formula theorem inside this Lean
base.
-/
theorem SR15_REDUCTION_AUDIT_OPEN : True := by
  trivial

/--
Stage 15F Selberg/Weil sign-convention audit.

The current Lean foundation verifies that the Rees grading is arithmetic, but
does not derive the sign convention `Interior ↦ -1`, `Exit ↦ +1` from a
formal Selberg explicit-formula or Weil-correspondence theorem.  This named
checkpoint records the open/partial status required by the Stage 15 objective:
the finite signature theorem is proved conditional on the Stage 14 sign table,
while the arithmetic derivation of that sign table remains future structure.
-/
theorem SR15_SIGN_ARITHMETIC_OPEN : True := by
  trivial

/-- Stage 15 outcome: clean formula, true-sector sign, counterexample exclusion,
mixed-sign witnesses, and explicit audit of the remaining sign-convention input. -/
theorem stage15_outcome :
    (∀ x : E10,
      I_SR_Rees x x =
        E10_realSupportSum x ^ 2 -
          2 * (x PrimeIndex6.p2).re ^ 2) ∧
    (Matrix.rank M_Rees = 2 ∧
      ∃ pos neg zdim : ℕ,
        pos = 1 ∧ neg = 1 ∧ zdim = 2 ∧
          pos + neg = Matrix.rank M_Rees ∧
          zdim = Module.finrank ℝ (LinearMap.ker M_Rees.mulVecLin)) ∧
    Matrix.rank M_Rees = 2 ∧
    Module.finrank ℝ (LinearMap.ker M_Rees.mulVecLin) = 2 ∧
    (M_Rees_real_radical_direction_34 ∈ LinearMap.ker M_Rees.mulVecLin ∧
      M_Rees_real_radical_direction_45 ∈ LinearMap.ker M_Rees.mulVecLin ∧
      (∀ x : E10R,
        x ∈ LinearMap.ker M_Rees.mulVecLin →
          ∃ a b : ℝ,
            x = a • M_Rees_real_radical_direction_34 +
              b • M_Rees_real_radical_direction_45) ∧
      (∀ a b : ℝ,
        a • M_Rees_real_radical_direction_34 +
            b • M_Rees_real_radical_direction_45 = 0 →
          a = 0 ∧ b = 0)) ∧
    (∀ x : E10, P_SR_phys_true x → I_SR_Rees x x ≤ 0) ∧
    P_SR_phys_true PD_radical_witness ∧
    ¬ P_SR_phys_true partialSignCounterexample ∧
    ((∃ x : E10, 0 < I_SR_Rees x x) ∧
      (∃ y : E10, I_SR_Rees y y < 0) ∧
      (∃ r : E10, M_Rees_form_radical r ∧ r ≠ 0)) ∧
    True ∧
    True := by
  constructor
  · intro x
    exact I_SR_Rees_formula x
  constructor
  · exact M_Rees_signature
  constructor
  · exact M_Rees_rank
  constructor
  · exact M_Rees_real_kernel_finrank
  constructor
  · exact M_Rees_real_kernel_two_direction_certificate
  constructor
  · intro x hx
    exact P_SR_phys_true_sign x hx
  constructor
  · exact radical_witness_in_true_phys
  constructor
  · exact counterexample_not_in_true_phys
  constructor
  · exact M_Rees_signature_witnesses
  constructor
  · exact SR15_REDUCTION_AUDIT_OPEN
  · exact SR15_SIGN_ARITHMETIC_OPEN

#check M_Rees
#check M_Rees_apply
#check M_Rees_p2_p2
#check E10R
#check E10R_sum
#check M_Rees_mulVec_eq_zero_iff
#check M_Rees_real_kernel_criterion
#check M_Rees_real_radical_direction_34
#check M_Rees_real_radical_direction_45
#check M_Rees_real_kernel_generated
#check M_Rees_real_radical_directions_independent_coeffs
#check M_Rees_real_radical_directions_not_collinear
#check M_Rees_real_kernel_two_direction_certificate
#check M_Rees_realKernelEquiv
#check M_Rees_real_kernel_finrank
#check E10R_finrank
#check M_Rees_rank
#check M_Rees_quadR
#check M_Rees_signatureCoord
#check M_Rees_signatureCoord_quad
#check M_Rees_signatureCoord_inv_quad
#check M_Rees_signature
#check I_SR_Rees_formula
#check I_SR_Rees_bilinear_formula
#check M_Rees_quad_formula
#check M_Rees_form_radical
#check M_Rees_has_two_named_radical_directions
#check M_Rees_form_radical_iff
#check P_SR_phys_true
#check P_SR_phys_true_arithmetic_char
#check P_SR_phys_true_nonempty
#check radical_witness_in_true_phys
#check counterexample_not_in_true_phys
#check M_Rees_signature_witnesses
#check SR15_REDUCTION_AUDIT_OPEN
#check SR15_SIGN_ARITHMETIC_OPEN
#check stage15_outcome

end SR
