import SR_Valuation

namespace SR

/--
Positive natural associated to a visible singleton support label at `X=5/2`.
-/
def SupportIndex52.toPosNat (i : SupportIndex52) : PosNat :=
  match i with
  | SupportIndex52.p2 => PosNat.ofPrime 2 nat_prime_two

/-- Stage 9 constraints: Stage 8 plus a positive-domain valuation law. -/
def satisfies_stage9_constraints (f : E20_X52 →ₗ[ℂ] ℂ) : Prop :=
  satisfies_stage8_constraints f ∧
    ∃ v : PositiveArithmeticValuation,
      ∀ i j : SupportIndex52,
        f (q52 i j) =
          (((v.val i.toPosNat) * (v.val j.toPosNat) : ℝ) : ℂ)

/-- Value assigned to `q₂₂` by the logarithmic valuation of scale `c`. -/
noncomputable def stage9ScaleValue (c : PositiveScale) : ℂ :=
  (((c.1 * Real.log 2) ^ 2 : ℝ) : ℂ)

/-- Stage 9 family generated by positive logarithmic scales. -/
noncomputable def stage9Family (c : PositiveScale) : E20_X52 →ₗ[ℂ] ℂ :=
  orientationFunctional (stage9ScaleValue c)

theorem stage9ScaleValue_real (c : PositiveScale) :
    star (stage9ScaleValue c) = stage9ScaleValue c := by
  simp [stage9ScaleValue]

theorem stage9ScaleValue_re_nonneg (c : PositiveScale) :
    0 ≤ Complex.re (stage9ScaleValue c) := by
  change 0 ≤ (↑(((c.1 * Real.log 2) ^ 2 : ℝ)) : ℂ).re
  rw [Complex.ofReal_re]
  exact sq_nonneg (c.1 * Real.log 2)

theorem stage9Family_satisfies_stage8 (c : PositiveScale) :
    satisfies_stage8_constraints (stage9Family c) := by
  unfold stage9Family
  apply orientationFunctional_stage8_of_enriched_nonneg
  · exact (orientationFunctional_enriched_iff_real (stage9ScaleValue c)).mpr
      (stage9ScaleValue_real c)
  · exact stage9ScaleValue_re_nonneg c

theorem stage9Family_q22 (c : PositiveScale) :
    stage9Family c (q52 SupportIndex52.p2 SupportIndex52.p2) =
      stage9ScaleValue c := by
  rw [q52_p2p2]
  exact orientationFunctional_q22 (stage9ScaleValue c)

theorem stage9Family_valuation_law (c : PositiveScale) :
    ∃ v : PositiveArithmeticValuation,
      ∀ i j : SupportIndex52,
        stage9Family c (q52 i j) =
          (((v.val i.toPosNat) * (v.val j.toPosNat) : ℝ) : ℂ) := by
  refine ⟨logPositiveValuation c, ?_⟩
  intro i j
  cases i
  cases j
  rw [stage9Family_q22]
  simp [stage9ScaleValue, SupportIndex52.toPosNat, logPositiveValuation_two]
  ring

theorem stage9Family_satisfies_constraints (c : PositiveScale) :
    satisfies_stage9_constraints (stage9Family c) := by
  exact ⟨stage9Family_satisfies_stage8 c, stage9Family_valuation_law c⟩

theorem stage9Family_injective :
    Function.Injective stage9Family := by
  intro c d hfun
  have hq :
      stage9Family c (q52 SupportIndex52.p2 SupportIndex52.p2) =
        stage9Family d (q52 SupportIndex52.p2 SupportIndex52.p2) :=
    congrArg (fun f => f (q52 SupportIndex52.p2 SupportIndex52.p2)) hfun
  have hsq : (c.1 * Real.log 2) ^ 2 = (d.1 * Real.log 2) ^ 2 := by
    have hre := congrArg Complex.re hq
    rw [stage9Family_q22, stage9Family_q22] at hre
    change
      (↑(((c.1 * Real.log 2) ^ 2 : ℝ)) : ℂ).re =
        (↑(((d.1 * Real.log 2) ^ 2 : ℝ)) : ℂ).re at hre
    rw [Complex.ofReal_re, Complex.ofReal_re] at hre
    exact hre
  have hlog : 0 < Real.log (2 : ℝ) := by
    exact Real.log_pos (by norm_num)
  have hsum : 0 < c.1 * Real.log 2 + d.1 * Real.log 2 := by
    nlinarith [c.2, d.2, hlog]
  have hdiff : c.1 * Real.log 2 - d.1 * Real.log 2 = 0 := by
    have hprod :
        (c.1 * Real.log 2 - d.1 * Real.log 2) *
          (c.1 * Real.log 2 + d.1 * Real.log 2) = 0 := by
      nlinarith
    nlinarith
  have hc : c.1 = d.1 := by
    nlinarith [hlog]
  exact Subtype.ext hc

/-- Stage 9 moduli: positive logarithmic scale remains as a free parameter. -/
theorem stage9_moduli :
    ∃ family : PositiveScale → (E20_X52 →ₗ[ℂ] ℂ),
      Function.Injective family ∧
        ∀ c : PositiveScale, satisfies_stage9_constraints (family c) := by
  exact ⟨stage9Family, stage9Family_injective, stage9Family_satisfies_constraints⟩

/-- Under Stage 9 constraints, the old scale-family value on `q₂₂` is positive. -/
theorem stage9ScaleValue_re_pos (c : PositiveScale) :
    0 < Complex.re (stage9ScaleValue c) := by
  change 0 < (↑(((c.1 * Real.log 2) ^ 2 : ℝ)) : ℂ).re
  rw [Complex.ofReal_re]
  have hlog : 0 < Real.log (2 : ℝ) := by
    exact Real.log_pos (by norm_num)
  have hmul : 0 < c.1 * Real.log 2 := by
    exact mul_pos c.2 hlog
  nlinarith

/-- Unit scale normalization, `c = 1`. -/
def unitScale : PositiveScale :=
  ⟨1, by norm_num⟩

/--
Singleton explicit-formula compatibility at `X = 5/2`.

Because the visible support contains only the prime `2`, this is the local
form of the Mangoldt weight law `J(q_pp) = log(p)^2`.
-/
structure ExplicitFormulaCompat (f : E20_X52 →ₗ[ℂ] ℂ) where
  mangoldt_law :
    Complex.re (f (q52 SupportIndex52.p2 SupportIndex52.p2)) =
      Real.log 2 ^ 2

theorem unitScale_candidate_satisfies_stage9 :
    satisfies_stage9_constraints (stage9Family unitScale) :=
  stage9Family_satisfies_constraints unitScale

theorem unitScale_candidate_explicitFormula :
    ExplicitFormulaCompat (stage9Family unitScale) := by
  constructor
  rw [stage9Family_q22]
  change (↑(((1 * Real.log 2) ^ 2 : ℝ)) : ℂ).re = Real.log 2 ^ 2
  rw [Complex.ofReal_re]
  ring

theorem stage9Family_explicitFormula_forces_unit (c : PositiveScale)
    (h : ExplicitFormulaCompat (stage9Family c)) :
    c = unitScale := by
  have hsq : (c.1 * Real.log 2) ^ 2 = Real.log 2 ^ 2 := by
    have hm := h.mangoldt_law
    rw [stage9Family_q22] at hm
    change (↑(((c.1 * Real.log 2) ^ 2 : ℝ)) : ℂ).re =
      Real.log 2 ^ 2 at hm
    rw [Complex.ofReal_re] at hm
    exact hm
  have hlog : 0 < Real.log (2 : ℝ) := by
    exact Real.log_pos (by norm_num)
  have hsum : 0 < c.1 * Real.log 2 + Real.log 2 := by
    nlinarith [c.2, hlog]
  have hdiff : c.1 * Real.log 2 - Real.log 2 = 0 := by
    have hprod :
        (c.1 * Real.log 2 - Real.log 2) *
          (c.1 * Real.log 2 + Real.log 2) = 0 := by
      nlinarith
    nlinarith
  have hc : c.1 = 1 := by
    nlinarith [hlog]
  exact Subtype.ext hc

/-- Explicit formula compatibility pins the positive logarithmic scale. -/
theorem explicitFormula_pins_scale :
    ∃! c : PositiveScale, ExplicitFormulaCompat (stage9Family c) := by
  refine ⟨unitScale, unitScale_candidate_explicitFormula, ?_⟩
  intro c h
  exact stage9Family_explicitFormula_forces_unit c h

/-- Positive natural associated to a frozen `X=6` support label. -/
def SupportIndex6.toPosNat (i : SupportIndex6) : PosNat :=
  match i with
  | PrimeIndex6.p2 => ⟨2, by norm_num⟩
  | PrimeIndex6.p3 => ⟨3, by norm_num⟩
  | PrimeIndex6.p4 => ⟨4, by norm_num⟩
  | PrimeIndex6.p5 => ⟨5, by norm_num⟩

/--
Valuation product weights are symmetric on the full frozen `X=6` support.
This is the scalar kernel calculation behind antisymmetric descent.
-/
theorem valuation_forces_descent :
    ∀ v : PositiveArithmeticValuation,
    ∀ m n : SupportIndex6,
      v.val m.toPosNat * v.val n.toPosNat =
        v.val n.toPosNat * v.val m.toPosNat := by
  intro v m n
  ring

#check SupportIndex52.toPosNat
#check satisfies_stage9_constraints
#check stage9ScaleValue
#check stage9Family
#check stage9ScaleValue_real
#check stage9ScaleValue_re_nonneg
#check stage9Family_satisfies_stage8
#check stage9Family_q22
#check stage9Family_valuation_law
#check stage9Family_satisfies_constraints
#check stage9Family_injective
#check stage9_moduli
#check stage9ScaleValue_re_pos
#check unitScale
#check ExplicitFormulaCompat
#check unitScale_candidate_satisfies_stage9
#check unitScale_candidate_explicitFormula
#check stage9Family_explicitFormula_forces_unit
#check explicitFormula_pins_scale
#check SupportIndex6.toPosNat
#check valuation_forces_descent

end SR
