import SR_GNS

namespace SR

/-- The rational wall value `X = 5/2`. -/
def X52 : ℚ :=
  5 / 2

/--
The pre-orientation carrier at `X = 5/2`.

The frozen fact says the currently visible orientation moduli are generated by
the single `q₂₂` direction, so this local carrier is represented by its complex
coefficient.
-/
abbrev E20_X52 : Type :=
  ℂ

/-- The visible `q₂₂` coefficient in the `X = 5/2` pre-orientation carrier. -/
def q22_X52 : E20_X52 :=
  1

/--
Current frozen constraints imposed on a candidate orientation functional.

At this stage the visible constraint is only linearity along the `q₂₂`
pre-orientation line.  It intentionally does not determine the value on
`q₂₂`.
-/
def satisfies_all_frozen_constraints (b₂ : E20_X52 →ₗ[ℂ] ℂ) : Prop :=
  ∀ c : ℂ, b₂ (c • q22_X52) = c • b₂ q22_X52

/-- Dagger on the one-dimensional `X = 5/2` pre-orientation carrier. -/
def dagger_20_X52 (z : E20_X52) : E20_X52 :=
  star z

/--
Visible ordered basis coefficient at `X = 5/2`.

The current pre-orientation carrier only retains the `q₂₂` line; every other
ordered label is invisible at this stage.
-/
def q_X52 (m n : Nat) : E20_X52 :=
  if m = 2 ∧ n = 2 then q22_X52 else 0

theorem q_X52_grade_interior_zero :
    ∀ m n : Nat, grade m n X52 = ReesGrade.Interior → q_X52 m n = 0 := by
  intro m n hgrade
  by_cases hm : m = 2
  · by_cases hn : n = 2
    · subst m
      subst n
      norm_num [grade, X52] at hgrade
      cases hgrade
    · simp [q_X52, hm, hn]
  · simp [q_X52, hm]

/--
Enriched Gap 4 constraints: old line-scaling, dagger compatibility, and
vanishing on interior-grade visible basis directions.
-/
def satisfies_enriched_frozen_constraints (b₂ : E20_X52 →ₗ[ℂ] ℂ) : Prop :=
  satisfies_all_frozen_constraints b₂ ∧
    (∀ x : E20_X52, b₂ (dagger_20_X52 x) = star (b₂ x)) ∧
    (∀ m n : Nat, grade m n X52 = ReesGrade.Interior → b₂ (q_X52 m n) = 0)

/-- The orientation functional with `b₂(q₂₂) = lam`. -/
noncomputable def orientationFunctional (lam : ℂ) : E20_X52 →ₗ[ℂ] ℂ where
  toFun z := z * lam
  map_add' := by
    intro z w
    simp [add_mul]
  map_smul' := by
    intro a z
    simp [mul_assoc]

theorem orientationFunctional_q22 (lam : ℂ) :
    orientationFunctional lam q22_X52 = lam := by
  simp [orientationFunctional, q22_X52]

theorem orientationFunctional_satisfies_constraints (lam : ℂ) :
    satisfies_all_frozen_constraints (orientationFunctional lam) := by
  intro c
  exact (orientationFunctional lam).map_smul c q22_X52

theorem orientationFunctional_enriched_iff_real (lam : ℂ) :
    satisfies_enriched_frozen_constraints (orientationFunctional lam) ↔ star lam = lam := by
  constructor
  · intro h
    have hdag := h.2.1 q22_X52
    exact (by
      simpa [orientationFunctional, dagger_20_X52, q22_X52] using hdag.symm)
  · intro hreal
    refine ⟨orientationFunctional_satisfies_constraints lam, ?_, ?_⟩
    · intro x
      simp [orientationFunctional, dagger_20_X52, hreal]
    · intro m n hgrade
      rw [q_X52_grade_interior_zero m n hgrade]
      simp [orientationFunctional]

theorem orientationFunctional_not_enriched_I :
    ¬ satisfies_enriched_frozen_constraints (orientationFunctional Complex.I) := by
  intro h
  have hreal := (orientationFunctional_enriched_iff_real Complex.I).mp h
  norm_num [Complex.ext_iff] at hreal

theorem orientationFunctional_injective :
    Function.Injective orientationFunctional := by
  intro lam mu h
  have hq : orientationFunctional lam q22_X52 = orientationFunctional mu q22_X52 :=
    congrArg (fun f => f q22_X52) h
  simpa [orientationFunctional_q22] using hq

/--
The pre-orientation moduli at `X = 5/2` are parametrized by `ℂ`: every complex
number gives a valid orientation value on `q₂₂`, and distinct values give
distinct functionals.
-/
theorem orientation_moduli_X52 :
    ∃ (family : ℂ → (E20_X52 →ₗ[ℂ] ℂ)),
      Function.Injective family ∧
      ∀ lam : ℂ, satisfies_all_frozen_constraints (family lam) := by
  refine ⟨orientationFunctional, orientationFunctional_injective, ?_⟩
  intro lam
  exact orientationFunctional_satisfies_constraints lam

#check X52
#check E20_X52
#check q22_X52
#check satisfies_all_frozen_constraints
#check dagger_20_X52
#check q_X52
#check q_X52_grade_interior_zero
#check satisfies_enriched_frozen_constraints
#check orientationFunctional
#check orientationFunctional_q22
#check orientationFunctional_satisfies_constraints
#check orientationFunctional_enriched_iff_real
#check orientationFunctional_not_enriched_I
#check orientationFunctional_injective
#check orientation_moduli_X52

end SR
